routes/web.php
<?php

use App\Http\Controllers\Admin\DishCategoriesController as AdminDishCategoriesController;
use App\Http\Controllers\Admin\DishesController as AdminDishesController;
use App\Http\Controllers\Admin\InstitutionCategoriesController as AdminInstitutionCategoriesController;
use App\Http\Controllers\Admin\InstitutionsController as AdminInstitutionsController;
use App\Http\Controllers\Admin\PagesController as AdminPagesController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\DishesController;
use App\Http\Controllers\InstitutionsController;
use App\Http\Controllers\ItemsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [InstitutionsController::class, 'index'])->name('index');

Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/dishCategories', AdminDishCategoriesController::class)->except(['show']);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/institutionCategories', AdminInstitutionCategoriesController::class)->except(['show']);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/dishes', AdminDishesController::class);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/institutions', AdminInstitutionsController::class);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/pages', AdminPagesController::class)->only(['index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('client')->name('client')->resource('institutions', InstitutionsController::class)->only(['index', 'show']);
Route::prefix('client')->name('client')->middleware('auth')->resource('cards', CardsController::class)->only(['show', 'store']);
Route::prefix('client')->name('client')->middleware('auth')->resource('cards.items', ItemsController::class)->only(['store', 'destroy']);
Route::prefix('client')->name('client')->resource('dishes', DishesController::class)->only(['show']);

app/Models/Institution.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Institution extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'picture', 'desc', 'institution_category_id'];

    /**
     * @return HasMany
     */
    public function dishes()
    {
        return $this->hasMany(Dish::class);
    }

    /**
     * @return BelongsTo
     */
    public function institutionCategory()
    {
        return $this->belongsTo(InstitutionCategory::class);
    }

    /**
     * @return HasMany
     */
    public function cards()
    {
        return $this->hasMany(Card::class);
    }
}

app/Http/Controllers/Admin/InstitutionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\InstitutionRequest;
use App\Models\Institution;
use App\Models\InstitutionCategory;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class InstitutionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('viewAny');
        $institutions = Institution::all();
        return view('admin.institutions.index', compact('institutions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('viewAny');
        $instCategories = InstitutionCategory::all();
        return view('admin.institutions.create', compact('instCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param InstitutionRequest $request
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(InstitutionRequest $request)
    {
        $this->authorize('viewAny');
        $institution = new Institution($request->all());
        if ($request->hasFile('picture')){
            $institution->picture = $request->file('picture')->store('pictures', 'public');
        }
        $institution->save();
        return redirect()->route('admin.institutions.index')->with('status', 'institution created!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Institution $institution
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Institution $institution)
    {
        $this->authorize('viewAny');
        return view('admin.institutions.show', compact('institution'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Institution $institution
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Institution $institution)
    {
        $this->authorize('viewAny');
        $instCategories = InstitutionCategory::all();
        return view('admin.institutions.edit', compact('institution', 'instCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param InstitutionRequest $request
     * @param \App\Models\Institution $institution
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(InstitutionRequest $request, Institution $institution)
    {
        $this->authorize('viewAny');
        $data = $request->all();
        if ($request->hasFile('picture')){
            $path = $request->file('picture')->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $institution->update($data);
        return redirect()->route('admin.institutions.index')->with('status', 'institution updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Institution $institution
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Institution $institution)
    {
        $this->authorize('viewAny');
        $institution->delete();
        return redirect()->route('admin.institutions.index')->with('status', 'institution deleted!');
    }
}

app/Http/Controllers/InstitutionsController.php
<?php

namespace App\Http\Controllers;

use App\Models\DishCategory;
use App\Models\Institution;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class InstitutionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     */
    public function index()
    {
        $institutions = Institution::all();
        return view('client.institutions.index', compact('institutions'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Institution  $institution
     * @return Factory|View|Response
     */
    public function show(Institution $institution)
    {
        return view('client.institutions.show', compact('institution'));
    }
}

resources/views/admin/institutions/create.blade.php
@extends('layouts.admin')

@section('content')

    <form enctype="multipart/form-data" action="{{route('admin.institutions.store')}}" method="post">
        @csrf

        <div class="form-group">
            <label for="name">name</label>
            <input type="text" class="form-control" id="name" name="name">
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="desc">Description</label>
            <textarea class="form-control" id="desc" name="desc"></textarea>
            @error('desc')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <select class="custom-select" name="institution_category_id">
                @foreach($instCategories as $instCat)
                    <option value="{{$instCat->id}}">{{$instCat->name}}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile" name="picture">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            @error('picture')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

@endsection

resources/views/admin/institutions/edit.blade.php
@extends('layouts.admin')

@section('content')

    <form enctype="multipart/form-data" action="{{route('admin.institutions.update', ['institution' => $institution])}}" method="post">
        @csrf
        @method('put')

        <div class="form-group">
            <label for="name">name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{$institution->name}}">
            @error('name')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="desc">Description</label>
            <textarea class="form-control" id="desc" name="desc">{{$institution->desc}}</textarea>
            @error('desc')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <select class="custom-select" name="institution_category_id">
                @foreach($instCategories as $instCat)
                    <option @if($institution->institution_category_id == $instCat->id) selected @endif value="{{$instCat->id}}">{{$instCat->name}}</option>
                @endforeach
            </select>
        </div>
        <img src="{{asset('/storage/' . $institution->picture)}}" alt="{{$institution->picture}}" style="width:100px;height:100px;"><br/><br>
        <div class="form-group">
            <div class="custom-file">
                <input type="file" class="custom-file-input" id="customFile" name="picture">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            @error('picture')
            <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <br>
        <button type="submit" class="btn btn-primary">Submit</button>

    </form>

@endsection

resources/views/admin/institutions/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>All Institutions</h1>
    <a href="{{route('admin.institutions.create')}}">Create new institution</a>

    @if($institutions->count()>0)

        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Picture</th>
                <th scope="col">Description</th>
                <th scope="col">Category</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach($institutions as $institution)
                <tr>
                    <th scope="row">{{$institution->id}}</th>
                    <td>{{$institution->name}}</td>
                    <td>
                        <img width="50px" height="50px" src="{{asset('/storage/' . $institution->picture)}}" alt="{{asset('/storage/' . $institution->picture)}}">
                    </td>
                    <td>{{$institution->desc}}</td>
                    <td>{{$institution->institutionCategory->name}}</td>
                    <td>
                        <a style="float: left" href="{{route('admin.institutions.edit', ['institution' => $institution])}}"><button type="submit" class="btn btn-outline-warning">Edit</button></a>

                        <a style="float: left" href="{{route('admin.institutions.show', ['institution' => $institution])}}"><button type="submit" class="btn btn-outline-success">Show</button></a>

                        <form style="float: left" method="post" action="{{route('admin.institutions.destroy', ['institution' => $institution])}}">
                            @method('delete')
                            @csrf
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>


    @else
        <p>no institutions</p>
    @endif

@endsection

resources/views/admin/institutions/show.blade.php
@extends('layouts.admin')

@section('content')

    <h1>{{lcfirst($institution->name)}}</h1>

    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{asset('/storage/' . $institution->picture)}}" class="img-fluid rounded-start" alt="{{asset('/storage/' . $institution->picture)}}">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{$institution->name}}</h5>
                    <p class="card-text">{{$institution->desc}}</p>
                    <p class="card-text">{{$institution->institutionCategory->name}}</p>
                </div>
            </div>
        </div>
    </div>

@endsection