routes/web.php
<?php

use App\Http\Controllers\Admin\DishCategoriesController as AdminDishCategoriesController;
use App\Http\Controllers\Admin\DishesController as AdminDishesController;
use App\Http\Controllers\Admin\InstitutionCategoriesController as AdminInstitutionCategoriesController;
use App\Http\Controllers\Admin\InstitutionsController as AdminInstitutionsController;
use App\Http\Controllers\Admin\PagesController as AdminPagesController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\DishesController;
use App\Http\Controllers\InstitutionsController;
use App\Http\Controllers\ItemsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [InstitutionsController::class, 'index'])->name('index');

Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/dishCategories', AdminDishCategoriesController::class)->except(['show']);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/institutionCategories', AdminInstitutionCategoriesController::class)->except(['show']);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/dishes', AdminDishesController::class);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/institutions', AdminInstitutionsController::class);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/pages', AdminPagesController::class)->only(['index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('client')->name('client')->resource('institutions', InstitutionsController::class)->only(['index', 'show']);
Route::prefix('client')->name('client')->middleware('auth')->resource('cards', CardsController::class)->only(['show', 'store']);
Route::prefix('client')->name('client')->middleware('auth')->resource('cards.items', ItemsController::class)->only(['store', 'destroy']);
Route::prefix('client')->name('client')->resource('dishes', DishesController::class)->only(['show']);

app/Models/InstitutionCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class InstitutionCategory extends Model
{
    use HasFactory;

    protected $fillable = ['name'];

    /**
     * @return HasMany
     */
    public function institutions()
    {
        return $this->hasMany(Institution::class);
    }
}

app/Http/Controllers/Admin/InstitutionCategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\InstitutionCategoryRequest;
use App\Models\InstitutionCategory;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class InstitutionCategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('viewAny');
        $instCategories = InstitutionCategory::all();
        return view('admin.institutionCategories.index', compact('instCategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('viewAny');
        return view('admin.institutionCategories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param InstitutionCategoryRequest $request
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(InstitutionCategoryRequest $request)
    {
        $this->authorize('viewAny');
        $instCategory = new InstitutionCategory($request->all());
        $instCategory->save();
        return redirect()->route('admin.institutionCategories.index')->with('status', 'institution category created!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\InstitutionCategory $institutionCategory
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(InstitutionCategory $institutionCategory)
    {
        $this->authorize('viewAny');
        return view('admin.institutionCategories.show', compact('institutionCategory'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\InstitutionCategory $institutionCategory
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(InstitutionCategory $institutionCategory)
    {
        $this->authorize('viewAny');
        return view('admin.institutionCategories.edit', compact('institutionCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param InstitutionCategoryRequest $request
     * @param \App\Models\InstitutionCategory $institutionCategory
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(InstitutionCategoryRequest $request, InstitutionCategory $institutionCategory)
    {
        $this->authorize('viewAny');
        $institutionCategory->update($request->all());
        return redirect()->route('admin.institutionCategories.index')->with('status', 'institution category updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\InstitutionCategory $institutionCategory
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(InstitutionCategory $institutionCategory)
    {
        $this->authorize('viewAny');
        $institutionCategory->delete();
        return redirect()->route('admin.institutionCategories.index')->with('status', 'institution category deleted!');
    }
}

resources/views/admin/institutionCategories/create.blade.php
@extends('layouts.admin')

@section('content')

    <form action="{{route('admin.institutionCategories.store')}}" method="post">
        @csrf

        <label class="col-form-label" for="name">Institution Category Name:</label>
        <input class="form-control col-6" type="text" id="name" name="name">
        @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <br>
        <button type="submit" class="btn btn-primary">Save</button>

    </form>

@endsection

resources/views/admin/institutionCategories/edit.blade.php
@extends('layouts.admin')

@section('content')

    <form action="{{route('admin.institutionCategories.update', ['institutionCategory' => $institutionCategory])}}" method="post">
        @csrf
        @method('put')

        <label class="col-form-label" for="name">Institution Category Name:</label>
        <input class="form-control col-6" type="text" id="name" name="name" value="{{$institutionCategory->name}}">
        @error('name')
        <div class="alert alert-danger">{{ $message }}</div>
        @enderror
        <br>
        <button type="submit" class="btn btn-primary">Save</button>

    </form>

@endsection

resources/views/admin/institutionCategories/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>All Institution Categories:</h1>

    <a href="{{route('admin.institutionCategories.create')}}">Create new institution category</a>

    <br>
    <br>

    @if($instCategories->count()>0)

        <ol>
            @foreach($instCategories as $instCat)
                <li>
                    <h4>
                        {{$instCat->name}}
                        <br>
                        <a href="{{route('admin.institutionCategories.edit', ['institutionCategory' => $instCat])}}">
                            <button class="btn btn-warning">Edit</button> </a>
                        <form class="my-1" action="{{route('admin.institutionCategories.destroy', ['institutionCategory' => $instCat])}}" method="post">
                            @csrf
                            @method('delete')
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </h4>
                </li>
            @endforeach
        </ol>
    @else

        <p>no institution categories</p>

    @endif

@endsection