routes/web.php
<?php

use App\Http\Controllers\Admin\DishCategoriesController as AdminDishCategoriesController;
use App\Http\Controllers\Admin\DishesController as AdminDishesController;
use App\Http\Controllers\Admin\InstitutionCategoriesController as AdminInstitutionCategoriesController;
use App\Http\Controllers\Admin\InstitutionsController as AdminInstitutionsController;
use App\Http\Controllers\Admin\PagesController as AdminPagesController;
use App\Http\Controllers\CardsController;
use App\Http\Controllers\DishesController;
use App\Http\Controllers\InstitutionsController;
use App\Http\Controllers\ItemsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [InstitutionsController::class, 'index'])->name('index');

Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/dishCategories', AdminDishCategoriesController::class)->except(['show']);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/institutionCategories', AdminInstitutionCategoriesController::class)->except(['show']);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/dishes', AdminDishesController::class);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/institutions', AdminInstitutionsController::class);
Route::prefix('admin')->name('admin')->middleware('auth')->resource('admin/pages', AdminPagesController::class)->only(['index']);

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::prefix('client')->name('client')->resource('institutions', InstitutionsController::class)->only(['index', 'show']);
Route::prefix('client')->name('client')->middleware('auth')->resource('cards', CardsController::class)->only(['show', 'store']);
Route::prefix('client')->name('client')->middleware('auth')->resource('cards.items', ItemsController::class)->only(['store', 'destroy']);
Route::prefix('client')->name('client')->resource('dishes', DishesController::class)->only(['show']);

app/Models/Institution.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Institution extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'picture', 'desc', 'institution_category_id'];

    /**
     * @return HasMany
     */
    public function dishes()
    {
        return $this->hasMany(Dish::class);
    }

    /**
     * @return BelongsTo
     */
    public function institutionCategory()
    {
        return $this->belongsTo(InstitutionCategory::class);
    }

    /**
     * @return HasMany
     */
    public function cards()
    {
        return $this->hasMany(Card::class);
    }
}

app/Http/Controllers/Admin/InstitutionsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\InstitutionRequest;
use App\Models\Institution;
use App\Models\InstitutionCategory;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class InstitutionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('viewAny');
        $institutions = Institution::all();
        return view('admin.institutions.index', compact('institutions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $this->authorize('viewAny');
        $instCategories = InstitutionCategory::all();
        return view('admin.institutions.create', compact('instCategories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param InstitutionRequest $request
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(InstitutionRequest $request)
    {
        $this->authorize('viewAny');
        $institution = new Institution($request->all());
        if ($request->hasFile('picture')){
            $institution->picture = $request->file('picture')->store('pictures', 'public');
        }
        $institution->save();
        return redirect()->route('admin.institutions.index')->with('status', 'institution created!');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Models\Institution $institution
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Institution $institution)
    {
        $this->authorize('viewAny');
        return view('admin.institutions.show', compact('institution'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\Institution $institution
     * @return Factory|View|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Institution $institution)
    {
        $this->authorize('viewAny');
        $instCategories = InstitutionCategory::all();
        return view('admin.institutions.edit', compact('institution', 'instCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param InstitutionRequest $request
     * @param \App\Models\Institution $institution
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(InstitutionRequest $request, Institution $institution)
    {
        $this->authorize('viewAny');
        $data = $request->all();
        if ($request->hasFile('picture')){
            $path = $request->file('picture')->store('pictures', 'public');
            $data['picture'] = $path;
        }
        $institution->update($data);
        return redirect()->route('admin.institutions.index')->with('status', 'institution updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Models\Institution $institution
     * @return \Illuminate\Http\RedirectResponse|Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Institution $institution)
    {
        $this->authorize('viewAny');
        $institution->delete();
        return redirect()->route('admin.institutions.index')->with('status', 'institution deleted!');
    }
}

app/Http/Controllers/InstitutionsController.php
<?php

namespace App\Http\Controllers;

use App\Models\DishCategory;
use App\Models\Institution;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class InstitutionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     */
    public function index()
    {
        $institutions = Institution::all();
        return view('client.institutions.index', compact('institutions'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Institution  $institution
     * @return Factory|View|Response
     */
    public function show(Institution $institution)
    {
        return view('client.institutions.show', compact('institution'));
    }
}

resources/views/client/institutions/index.blade.php
@extends('layouts.client')

@section('content')

    <div style="display: none">
        <p>Anton postavit 10 ballov</p>
    </div>

    <div class="container">
        <h1>All Institutions</h1>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 justify-content-center">
            @foreach($institutions->sortBy('institution_category_id') as $inst)

                <div class="d-flex col mb-3">
                    <div class="card">
                        <div class="card-img">
                            <a href="{{route('client.institutions.show', ['institution' => $inst])}}">
                                <img src="{{asset('/storage/' . $inst->picture)}}" class="card-img-top" alt="{{asset('/storage/' . $inst->picture)}}">
                            </a>
                        </div>
                        <div class="card-body d-flex flex-column">
                            <h5 class="card-title"><a href="{{route('client.institutions.show', ['institution' => $inst])}}">{{$inst->name}} | {{$inst->institutionCategory->name}}</a></h5>
                            <p class="card-text">{{$inst->desc}}</p>
                        </div>
                    </div>
                </div>

            @endforeach
        </div>
    </div>
@endsection

resources/views/client/institutions/show.blade.php
@extends('layouts.client')

@section('cardcontent')

        <li>
                @if(!is_null(\App\Models\Card::where('user_id', \Illuminate\Support\Facades\Auth::user()->id)->where('institution_id', $institution->id)->get()->last()))
                <form action="{{route('client.cards.show', ['card' => \App\Models\Card::where('user_id', \Illuminate\Support\Facades\Auth::user()->id)->where('institution_id', $institution->id)->get()->last()])}}" method="post">
                    @csrf
                    @method('get')
                    <button type="submit" class="btn btn-outline-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                        </svg></button>
                </form>
            @else
                <form action="{{route('client.cards.store')}}" method="post">
                    @csrf

                    <input type="hidden" name="institution_id" value="{{$institution->id}}">

                    <button type="submit" class="btn btn-outline-success"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart4" viewBox="0 0 16 16">
                            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
                        </svg></button>
                </form>
            @endif
        </li>

@endsection

@section('content')
    <div class="container">
        <h1>Order food at: {{$institution->name}} | {{$institution->institutionCategory->name}}</h1>

        <p>{{$institution->desc}}</p>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            @foreach($institution->dishes->sortBy('dish_category_id') as $dish)
                    <div class="col mb-2">
                        <div class="card">
                            <a href="{{route('client.dishes.show', ['dish' => $dish])}}">
                                <img src="{{asset('/storage/' . $dish->picture)}}" class="card-img-top" alt="{{asset('/storage/' . $dish->picture)}}">
                            </a>
                            <div class="card-body">
                                <h5>Category: {{$dish->dishCategory->name}}</h5>
                                <h4 class="card-title">
                                    <a href="{{route('client.dishes.show', ['dish' => $dish])}}">{{$dish->name}}</a>
                                </h4>
                                <h4 class="card-title">{{$dish->price}} som</h4>
                                <form class="order-dish-form-{{$dish->id}}">
                                    @csrf
                                    <input type="hidden" name="card_id" value="{{\App\Models\Card::where('user_id', \Illuminate\Support\Facades\Auth::user()->id)->where('institution_id', $institution->id)->get()->last()->id}}">
                                    <input type="hidden" name="dish_id" value="{{$dish->id}}">
                                    <input type="hidden" name="price" value="{{$dish->price}}">
                                    <input type="hidden" name="dish_name" value="{{$dish->name}}">
                                    <div class="form-group row">
                                        <label class="col-4" for="qty-{{$dish->id}}">Quantity:</label>
                                        <input min="0.5" type="number" step=".5" class="form-control col-3" id="qty-{{$dish->id}}" name="qty" value="1">
                                        @error('price')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                        @enderror
                                    </div>
                                    @auth()
                                        <button type="submit" class="btn btn-outline-success order-dish-btn" data-dish-id="{{$dish->id}}"
                                                data-card-id="{{ Auth::user()->cards->last()->id }}">Add to Cart</button>
                                    @endauth
                                    <a href="{{ route('client.dishes.show', ['dish' => $dish]) }}" class="btn btn-outline-info">About Dish</a>
                                </form>
                            </div>
                        </div>
                    </div>
            @endforeach
        </div>
    </div>
@endsection